import type { Metadata } from "next";
import { Montserrat_Alternates, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import { SearchProvider } from "./components/SearchContext/SearchContext";
import SideBar from "./components/SideBar/SideBar";



const montserratAlt = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
  variable: "--font-montserrat-alternates"
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"]
})




export const metadata: Metadata = {
  title: "SugarMates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" className={montserratAlt.className}>
        <body>
          <SearchProvider>
        <Header/>
        <main>
          <SideBar/>
          {children}
        </main>
        </SearchProvider>
      </body>
    </html>
  );
}
